[debug] [2020-04-26T21:32:53.287Z] ----------------------------------------------------------------------
[debug] [2020-04-26T21:32:53.294Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-26T21:32:53.295Z] CLI Version:   8.1.1
[debug] [2020-04-26T21:32:53.295Z] Platform:      win32
[debug] [2020-04-26T21:32:53.296Z] Node Version:  v12.16.2
[debug] [2020-04-26T21:32:53.320Z] Time:          Mon Apr 27 2020 00:32:53 GMT+0300 (GMT+03:00)
[debug] [2020-04-26T21:32:53.321Z] ----------------------------------------------------------------------
[debug] [2020-04-26T21:32:53.321Z] 
[debug] [2020-04-26T21:32:53.356Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-26T21:32:53.462Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-26T21:35:48.436Z] ----------------------------------------------------------------------
[debug] [2020-04-26T21:35:48.441Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-26T21:35:48.441Z] CLI Version:   8.1.1
[debug] [2020-04-26T21:35:48.442Z] Platform:      win32
[debug] [2020-04-26T21:35:48.442Z] Node Version:  v12.16.2
[debug] [2020-04-26T21:35:48.443Z] Time:          Mon Apr 27 2020 00:35:48 GMT+0300 (GMT+03:00)
[debug] [2020-04-26T21:35:48.444Z] ----------------------------------------------------------------------
[debug] [2020-04-26T21:35:48.444Z] 
[debug] [2020-04-26T21:35:48.470Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-26T21:35:48.534Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-26T21:36:06.240Z] ----------------------------------------------------------------------
[debug] [2020-04-26T21:36:06.245Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-26T21:36:06.246Z] CLI Version:   8.1.1
[debug] [2020-04-26T21:36:06.246Z] Platform:      win32
[debug] [2020-04-26T21:36:06.246Z] Node Version:  v12.16.2
[debug] [2020-04-26T21:36:06.249Z] Time:          Mon Apr 27 2020 00:36:06 GMT+0300 (GMT+03:00)
[debug] [2020-04-26T21:36:06.249Z] ----------------------------------------------------------------------
[debug] [2020-04-26T21:36:06.249Z] 
[debug] [2020-04-26T21:36:06.271Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-26T21:36:06.330Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-26T21:41:19.698Z] ----------------------------------------------------------------------
[debug] [2020-04-26T21:41:19.704Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2020-04-26T21:41:19.705Z] CLI Version:   8.1.1
[debug] [2020-04-26T21:41:19.705Z] Platform:      win32
[debug] [2020-04-26T21:41:19.705Z] Node Version:  v12.16.2
[debug] [2020-04-26T21:41:19.726Z] Time:          Mon Apr 27 2020 00:41:19 GMT+0300 (GMT+03:00)
[debug] [2020-04-26T21:41:19.727Z] ----------------------------------------------------------------------
[debug] [2020-04-26T21:41:19.727Z] 
[debug] [2020-04-26T21:41:19.758Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-26T21:41:19.858Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\Никиточка\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
